### ISSUE TITLE
Consider intergrating into ga-bos core

### ISSUE THREAD

**Issue by RealWeeks** [jenweber/callback-workshop#2]
This is really good @jenweber mind if i integrate it into the ga-boston core organization for possible use next cohort? I'll keep the commit history so it credits you with the creation.

**Comment by jenweber** [comment]
Sure, glad to know it will be useful. You or the other instructors may want to talk to Jason L too - he had some great ideas about what kind of examples to use in the demo, and how to scale the difficulty as the lesson went on (starting with console logs, and ending on using a new method like foreach or reduce, etc). We might work on it a little more after final projects. I'll let you know if that's the case.
